apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shortener-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
spec:
  replicas: 1
  selector:
    matchLabels:  # Tell which pods this deployment manages
      app: shortener
  template:
    metadata:
      labels:  # Apply labels for pod
        app: shortener
    spec:
      containers:
        - name: shortener
          image: go-service
          imagePullPolicy: Never # https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
          ports:
            - containerPort: 8080
          env:
            - name: DATA_PATH
              value: /data
          volumeMounts:
            - name: storage
              mountPath: /data # path inside pod
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: shortener-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shortener
spec:
  selector:
    app: shortener
  ports:
    - port: 8080
      targetPort: 8080
